### ISSUE TITLE
A kind and humble instalation error report 

### ISSUE THREAD

**Issue by Erickfeio** [jonatasgrosman/findpapers#5]
Hello there. This is a report for an instalation error. I was trying to install the FindPapers and this happened.
![image](https://user-images.githubusercontent.com/94879246/218121900-b5532cdf-5f66-4465-9fa3-11a761302f96.png)

I am using python-3.11.2-amd64.
Windows 10.
Thank you. This project seems a lot useful. <3

**Comment by Erickfeio** [comment]
Update: 
I am trying now to use it on Google Colab, but when I try to refine I can't select the options.
![image](https://user-images.githubusercontent.com/94879246/218286773-b7c1ef3a-28c0-49d3-a95e-12c26cc3ab22.png)
Does someone have a solution?

**Comment by jonatasgrosman** [comment]
Hi @Erickfeio,

### About your installation issue:

![image](https://user-images.githubusercontent.com/5097052/218361364-5b56e05c-3ad7-4a99-9928-927a33a28aae.png)

... As you can see in the log, you need to install the cpp-build-tools using the provided link. This installation error is probably due to your environment's lack of GCC compiler. This is needed to install one of the findpapers requirements, more precisely, the edlib

### About the colab issue:

Currently, Findpapers only works correctly when you use a standard terminal, its behavior in another type of terminal (such as in Google Colab) is unstable.

**Comment by Erickfeio** [comment]
Thank you! It worked wonderfully. 😁
